CREATE DATABASE ANIMALS

USE ANIMALS

CREATE TABLE DOGS(
	ID INTEGER PRIMARY KEY IDENTITY,
	NAME VARCHAR(50) NOT NULL
 )
 GO
 CREATE TABLE CATS(
	ID INTEGER PRIMARY KEY IDENTITY,
	NAME VARCHAR(50) NOT NULL
 )
 GO

 INSERT INTO DOGS VALUES('TOBI')
 INSERT INTO DOGS VALUES('TOBI')
 INSERT INTO DOGS VALUES('ARIEL')
 INSERT INTO DOGS VALUES('YORRA')
 INSERT INTO DOGS VALUES('DARANA')
 INSERT INTO DOGS VALUES('LAIKA')
 INSERT INTO DOGS VALUES('DARANA')
 INSERT INTO DOGS VALUES('MIKE')

 SELECT * FROM DOGS


 INSERT INTO CATS VALUES ('CREPUSCULO')
 INSERT INTO CATS VALUES ('AURORA')
 INSERT INTO CATS VALUES ('FELIX')
 INSERT INTO CATS VALUES ('TOM')
 INSERT INTO CATS VALUES ('TOM')
 INSERT INTO CATS VALUES ('HORUS')
 INSERT INTO CATS VALUES ('HELINHO')
 INSERT INTO CATS VALUES ('LUA')
 INSERT INTO CATS VALUES ('TOM')

 SELECT * FROM CATS 

 SELECT DISTINCT NAME FROM DOGS 
 UNION 
 SELECT DISTINCT NAME FROM CATS