create database questio6db
go
use questio6db
go


CREATE TABLE STUDENTS(
	IDSTUDENT INT PRIMARY KEY IDENTITY,
	NAME VARCHAR(30) NOT NULL,
	VALUE INT,
	ID_NOTES INT
)
GO


/*A GRADE CAN BELONG TO MORE THAN ONE STUDENT, 1XN*/

CREATE TABLE NOTES(
	IDNOTES INT PRIMARY KEY IDENTITY,
	GRADE INT,
	MIN_VALUE INT,
	MAX_VALUE INT,
)
GO


ALTER TABLE STUDENTS ADD CONSTRAINT FK_STUDENTS_NOTES
FOREIGN KEY(ID_NOTES) REFERENCES NOTES(IDNOTES)

INSERT INTO NOTES VALUES (1,0,9)
INSERT INTO NOTES VALUES (2,10,19)
INSERT INTO NOTES VALUES (3,20,29)
INSERT INTO NOTES VALUES (4,30,39)
INSERT INTO NOTES VALUES (5,40,49)
INSERT INTO NOTES VALUES (6,50,59)
INSERT INTO NOTES VALUES (7,60,69)
INSERT INTO NOTES VALUES (8,70,79)
INSERT INTO NOTES VALUES (9,80,89)
INSERT INTO NOTES VALUES (10,90,100)

SELECT * FROM NOTES 
GO

INSERT INTO STUDENTS VALUES('JULIA',81,9)
INSERT INTO STUDENTS VALUES('CAROL',68, 7)
INSERT INTO STUDENTS VALUES('MARIA',99, 10)
INSERT INTO STUDENTS VALUES('ANDREIA',78, 8)
INSERT INTO STUDENTS VALUES('JAQUELINE',63, 7)
INSERT INTO STUDENTS VALUES('MARCELA',88, 9)
GO

SELECT * FROM STUDENTS
GO


SELECT S.IDSTUDENT AS 'ID', 
CASE 
	WHEN N.GRADE<8 THEN NULL
	ELSE S.NAME
END AS 'NAME',
S.VALUE, N.GRADE
FROM NOTES N
INNER JOIN STUDENTS S
ON N.IDNOTES = S.ID_NOTES 
ORDER BY N.GRADE DESC
 
